//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDauGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apprais
    {
        public string Assessor { get; set; }
        public string BeAsssessed { get; set; }
        public string Remark { get; set; }
        public System.DateTime TimeAppraise { get; set; }
        public int ProID { get; set; }
        public bool Scores { get; set; }
        public int AppID { get; set; }
    }
}
